TRAIN_DATA_PATH = '../../data/processed/train_data.json'
TRAIN_DATA_LENGTH = 70484
VALID_DATA_PATH = '../../data/processed/validation_data.json'
VALID_DATA_LENGTH = 10570
TEST_DATA_PATH = '../../data/processed/test_data.json'
TEST_DATA_LENGTH = 11877
PRE_TRAINED_EMBEDDING_PATH = '../data/glove.840B.300d.txt'
WORD_DIM = 300
PRE_TRAINED_EMBEDDING = False
WORD2VEC_EMBEDDING = True
WORD_SIZE = None
NON_TRAINABLE = True
BATCH_SIZE = 32
HIDDEN_SIZE = 128
N_EPOCHS = 1000000
CLIP = 5
LEARNING_RATE = 0.001
MOMENTUM = 0.7


